@base = http://localhost:3000
@baseRemote = https://ws-project-2.onrender.com

// CUSTOMERS routes

### list customers in DB
get {{base}}/customers

### insert new customer to DB
post {{base}}/customers/writeNewCustomer HTTP/1.1 
content-type: application/json

{
    "firstName":"Marshall",
    "lastName":"Mathers",
    "email":"pottymouth@eminem.com",
    "phoneNumber":"123-555-2345",
    "lastOrderDate":"2025-10-13"
}

### update customer in DB
put {{base}}/customers/updateCustomer/68ed60e14244ffa80b71dbde HTTP/1.1 
content-type: application/json

{
    "firstName":"Marshall",
    "lastName":"Mathers",
    "email":"pottymouth@eminem.com",
    "phoneNumber":"123-555-0000",
    "lastOrderDate":"2025-10-13"
}

### delete customer in DB
delete {{base}}/customers/deleteCustomer/68ed60e14244ffa80b71dbde HTTP/1.1

// ORDERS routes







// REMOTE TESTS ON RENDER

### list customers in DB - RENDER
get {{baseRemote}}/customers

### insert new customer to DB - RENDER
post {{baseRemote}}/customers/writeNewCustomer HTTP/1.1 
content-type: application/json

{
    "firstName":"Marshall",
    "lastName":"Mathers",
    "email":"pottymouth@eminem.com",
    "phoneNumber":"123-555-2345",
    "lastOrderDate":"2025-10-13"
}

### update customer in DB - RENDER
put {{baseRemote}}/customers/updateCustomer/68ed60e14244ffa80b71dbde HTTP/1.1 
content-type: application/json

{
    "firstName":"Marshall",
    "lastName":"Mathers",
    "email":"pottymouth@eminem.com",
    "phoneNumber":"123-555-0000",
    "lastOrderDate":"2025-10-13"
}

### delete customer in DB - RENDER
delete {{baseRemote}}/customers/deleteCustomer/68ed60e14244ffa80b71dbde HTTP/1.1